/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as AboutRouteImport } from './routes/about'
import { Route as NotFoundRouteImport } from './routes/NotFound'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIdRouteImport } from './routes/studio.$id'
import { Route as ProjectIdRouteImport } from './routes/project.$id'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/NotFound',
  path: '/NotFound',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/studio/$id',
  path: '/studio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/NotFound': typeof NotFoundRoute
  '/about': typeof AboutRoute
  '/new': typeof NewRoute
  '/project/$id': typeof ProjectIdRoute
  '/studio/$id': typeof StudioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/NotFound': typeof NotFoundRoute
  '/about': typeof AboutRoute
  '/new': typeof NewRoute
  '/project/$id': typeof ProjectIdRoute
  '/studio/$id': typeof StudioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/NotFound': typeof NotFoundRoute
  '/about': typeof AboutRoute
  '/new': typeof NewRoute
  '/project/$id': typeof ProjectIdRoute
  '/studio/$id': typeof StudioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/NotFound'
    | '/about'
    | '/new'
    | '/project/$id'
    | '/studio/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/NotFound' | '/about' | '/new' | '/project/$id' | '/studio/$id'
  id:
    | '__root__'
    | '/'
    | '/NotFound'
    | '/about'
    | '/new'
    | '/project/$id'
    | '/studio/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  AboutRoute: typeof AboutRoute
  NewRoute: typeof NewRoute
  ProjectIdRoute: typeof ProjectIdRoute
  StudioIdRoute: typeof StudioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/NotFound': {
      id: '/NotFound'
      path: '/NotFound'
      fullPath: '/NotFound'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/studio/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  AboutRoute: AboutRoute,
  NewRoute: NewRoute,
  ProjectIdRoute: ProjectIdRoute,
  StudioIdRoute: StudioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
